"""require normalized JMdict reading search text

Revision ID: 119f3d0ae678
Revises: 80a9af5b6dc3
Create Date: 2026-09-18 11:52:22.610499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "119f3d0ae678"
down_revision: str | Sequence[str] | None = "80a9af5b6dc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jmdict_readings", "search_text", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jmdict_readings", "search_text", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###
