"""require normalized JMdict written form search text

Revision ID: 21bf67a5759e
Revises: 4150450e3f2b
Create Date: 2026-09-18 13:40:35.901635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21bf67a5759e"
down_revision: str | Sequence[str] | None = "4150450e3f2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jmdict_written_forms", "search_text", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jmdict_written_forms", "search_text", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###
