"""add JMdict sense usage tags

Revision ID: 2ff18ae5d691
Revises: 1d35359fc290
Create Date: 2026-09-23 21:06:52.387956

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ff18ae5d691"
down_revision: str | Sequence[str] | None = "1d35359fc290"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_misc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_jmdict_misc_positive_position"),
        sa.ForeignKeyConstraint(["sense_id"], ["jmdict_senses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sense_id", "position", name="uq_jmdict_misc_sense_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jmdict_misc")
    # ### end Alembic commands ###
