"""add jmdict readings

Revision ID: 68190d6898f2
Revises: 961dda14ba71
Create Date: 2026-09-17 13:42:03.572505

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68190d6898f2"
down_revision: str | Sequence[str] | None = "961dda14ba71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("no_kanji", sa.Boolean(), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_jmdict_readings_positive_position"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["jmdict_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entry_id", "position", name="uq_jmdict_readings_entry_position"
        ),
        sa.UniqueConstraint("entry_id", "text", name="uq_jmdict_readings_entry_text"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jmdict_readings")
    # ### end Alembic commands ###
