"""add normalized JMdict written form search text

Revision ID: 8c54599bbf70
Revises: 119f3d0ae678
Create Date: 2026-09-18 13:24:04.991761

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c54599bbf70"
down_revision: str | Sequence[str] | None = "119f3d0ae678"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jmdict_written_forms", sa.Column("search_text", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jmdict_written_forms", "search_text")
    # ### end Alembic commands ###
