"""add jmdict sense restrictions

Revision ID: 91d3167c67d9
Revises: f8951a121491
Create Date: 2026-09-17 14:52:02.417124

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91d3167c67d9"
down_revision: str | Sequence[str] | None = "f8951a121491"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_jmdict_senses_entry_id", "jmdict_senses", ["entry_id", "id"]
    )
    op.create_table(
        "jmdict_sense_reading_restrictions",
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("reading_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id", "reading_id"],
            ["jmdict_readings.entry_id", "jmdict_readings.id"],
            name="fk_jmdict_sense_reading_restrictions_target",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id", "sense_id"],
            ["jmdict_senses.entry_id", "jmdict_senses.id"],
            name="fk_jmdict_sense_reading_restrictions_sense",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sense_id", "reading_id"),
    )
    op.create_table(
        "jmdict_sense_written_form_restrictions",
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("written_form_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id", "sense_id"],
            ["jmdict_senses.entry_id", "jmdict_senses.id"],
            name="fk_jmdict_sense_written_form_restrictions_sense",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id", "written_form_id"],
            ["jmdict_written_forms.entry_id", "jmdict_written_forms.id"],
            name="fk_jmdict_sense_written_form_restrictions_target",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sense_id", "written_form_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("jmdict_sense_written_form_restrictions")
    op.drop_table("jmdict_sense_reading_restrictions")

    op.drop_constraint(
        "uq_jmdict_senses_entry_id",
        "jmdict_senses",
        type_="unique",
    )
