"""add jmdict entries and written forms

Revision ID: 961dda14ba71
Revises: 36159fa606da
Create Date: 2026-09-17 13:18:56.082753

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "961dda14ba71"
down_revision: str | Sequence[str] | None = "36159fa606da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", name="uq_jmdict_entries_source_id"),
    )
    op.create_table(
        "jmdict_written_forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position > 0", name="ck_jmdict_written_forms_positive_position"
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["jmdict_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entry_id", "position", name="uq_jmdict_written_forms_entry_position"
        ),
        sa.UniqueConstraint(
            "entry_id", "text", name="uq_jmdict_written_forms_entry_text"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jmdict_written_forms")
    op.drop_table("jmdict_entries")
    # ### end Alembic commands ###
