"""add jmdict references

Revision ID: b6020449e4df
Revises: f13eca1485ac
Create Date: 2026-10-01 00:09:05.807429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6020449e4df"
down_revision: str | Sequence[str] | None = "f13eca1485ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('xref', 'ant')", name="ck_jmdict_references_kind"),
        sa.CheckConstraint(
            "position > 0", name="ck_jmdict_references_positive_position"
        ),
        sa.ForeignKeyConstraint(["sense_id"], ["jmdict_senses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sense_id",
            "kind",
            "position",
            name="uq_jmdict_references_sense_kind_position",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jmdict_references")
    # ### end Alembic commands ###
