"""add jmdict loan sources and gloss qualifiers

Revision ID: c0d76f963889
Revises: b6020449e4df
Create Date: 2026-10-01 01:54:03.527133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0d76f963889"
down_revision: str | Sequence[str] | None = "b6020449e4df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_loan_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column(
            "wasei", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position > 0", name="ck_jmdict_loan_sources_positive_position"
        ),
        sa.ForeignKeyConstraint(["sense_id"], ["jmdict_senses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sense_id", "position", name="uq_jmdict_loan_sources_sense_position"
        ),
    )
    op.add_column("jmdict_glosses", sa.Column("gloss_type", sa.Text(), nullable=True))
    op.add_column("jmdict_glosses", sa.Column("gender", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jmdict_glosses", "gender")
    op.drop_column("jmdict_glosses", "gloss_type")
    op.drop_table("jmdict_loan_sources")
    # ### end Alembic commands ###
