"""add normalized JMdict reading search text

Revision ID: c13c62d24d17
Revises: da54e2a97971
Create Date: 2026-09-18 11:31:13.815762

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c13c62d24d17"
down_revision: str | Sequence[str] | None = "da54e2a97971"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jmdict_readings", sa.Column("search_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jmdict_readings", "search_text")
    # ### end Alembic commands ###
