"""add jmdict senses and glosses

Revision ID: d3f436a52bd5
Revises: ec2d75c43b4e
Create Date: 2026-09-17 14:17:00.882568

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3f436a52bd5"
down_revision: str | Sequence[str] | None = "ec2d75c43b4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_senses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_jmdict_senses_positive_position"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["jmdict_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entry_id", "position", name="uq_jmdict_senses_entry_position"
        ),
    )
    op.create_table(
        "jmdict_glosses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_jmdict_glosses_positive_position"),
        sa.ForeignKeyConstraint(["sense_id"], ["jmdict_senses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sense_id", "position", name="uq_jmdict_glosses_sense_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jmdict_glosses")
    op.drop_table("jmdict_senses")
    # ### end Alembic commands ###
