"""add jmdict entry commonness

Revision ID: da54e2a97971
Revises: 91d3167c67d9
Create Date: 2026-09-17 22:12:55.278550

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da54e2a97971"
down_revision: str | Sequence[str] | None = "91d3167c67d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jmdict_entries",
        sa.Column(
            "is_common", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jmdict_entries", "is_common")
    # ### end Alembic commands ###
