"""add jmdict form annotations

Revision ID: f13eca1485ac
Revises: ad16efffe753
Create Date: 2026-09-29 13:11:24.719712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f13eca1485ac"
down_revision: str | Sequence[str] | None = "ad16efffe753"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_reading_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reading_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position > 0", name="ck_jmdict_reading_info_positive_position"
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"], ["jmdict_readings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reading_id", "position", name="uq_jmdict_reading_info_position"
        ),
    )
    op.create_table(
        "jmdict_written_form_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("written_form_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position > 0", name="ck_jmdict_written_form_info_positive_position"
        ),
        sa.ForeignKeyConstraint(
            ["written_form_id"], ["jmdict_written_forms.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "written_form_id", "position", name="uq_jmdict_written_form_info_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jmdict_written_form_info")
    op.drop_table("jmdict_reading_info")
    # ### end Alembic commands ###
