"""add jmdict parts of speech

Revision ID: f8951a121491
Revises: d3f436a52bd5
Create Date: 2026-09-17 14:42:12.563877

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8951a121491"
down_revision: str | Sequence[str] | None = "d3f436a52bd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jmdict_parts_of_speech",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position > 0", name="ck_jmdict_parts_of_speech_positive_position"
        ),
        sa.ForeignKeyConstraint(["sense_id"], ["jmdict_senses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sense_id", "position", name="uq_jmdict_parts_of_speech_sense_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jmdict_parts_of_speech")
    # ### end Alembic commands ###
