[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.5",
    "pydantic>=2.13.5",
    "romkan2>=0.1.1",
    "sqlalchemy>=2.0.54",
]

[dependency-groups]
dev = [
    "httpx2>=2.13.0",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
